// src/App.tsx
import Search from "./Search";

const App: React.FC = () => {
    return <>
        <main className='max-w-full sm:max-w-280 pl-8 pr-8 pb-24 lg:pl-32 lg:pr-32 pt-8 ml-auto mr-auto'>
            <nav className='flex flex-row w-fill justify-end items-center'>
                <a className='ml-4 block' href='mailto:carsonalh@gmail.com'>
                    <svg xmlns='http://www.w3.org/2000/svg' className='size-7 fill-navy hover:fill-grey transition-colors duration-100' viewBox='0 0 512 512'>
                        <path d='M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48L48 64zM0 176L0 384c0 35.3 28.7 64 64 64l384 0c35.3 0 64-28.7 64-64l0-208L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z' />
                    </svg>
                </a>
                <a className='ml-4 block' href='https://github.com/carsonalh'>
                    <svg xmlns='http://www.w3.org/2000/svg' className='size-8 fill-navy hover:fill-grey transition-colors duration-100' viewBox='0 0 496 512'>
                        <path d='M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z' />
                    </svg>
                </a>
                <a className='ml-4 block' href='https://www.linkedin.com/in/carson-holloway-849b2b197/'>
                    <svg xmlns='http://www.w3.org/2000/svg' className='size-8 fill-navy hover:fill-grey transition-colors duration-100' viewBox='0 0 448 512'>
                        <path d='M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z' />
                    </svg>
                </a>
            </nav>

            <section className='mt-12'>
                <h1 className='font-extrabold text-navy text-4xl mb-4'>carson holloway</h1>
                <h2 className='text-grey text-2xl mb-3'>full-stack developer</h2>
                <h3 className='text-lightgrey text-xl mb-3'>brisbane, au</h3>
            </section>

            <section className='mt-12'>
                <h2 className='font-extrabold text-2xl text-navy mb-8'>my best technologies</h2>
                <ul className='grid grid-rows-2 grid-cols-2 items-end gap-y-6 sm:flex sm:flex-row sm:justify-evenly'>
                    <li className='flex flex-col gap-2 items-center text-grey'><img className='sm:max-h-28' src='nodejs.svg' />node js</li>
                    <li className='flex flex-col gap-2 items-center text-grey'><img className='sm:max-h-28' src='typescript.svg' />typescript</li>
                    <li className='flex flex-col gap-2 items-center text-grey'><img className='sm:max-h-28' src='react.svg' />react</li>
                    <li className='flex flex-col gap-2 items-center text-grey'><img className='sm:max-h-28' src='go.svg' />go</li>
                </ul>
            </section>

            <section className='mt-12'>
                <h2 className='font-extrabold text-2xl text-navy mb-2'>also excellent with</h2>
                <Search />
            </section>

            <section className='mt-12'>
                <h2 className='font-extrabold text-2xl text-navy mb-8'>want to learn more?</h2>
                <p className='text-navy'>
                    send me an
                    <a className='ml-1' href='mailto:carsonalh@gmail.com'><span className='underline'>email</span> <img className='size-3 inline mr-1' src='/arrow-up-right-from-square-solid.svg'/></a>,
                    message me on
                    <a className='ml-1' href='https://www.linkedin.com/in/carson-holloway-849b2b197/'><span className='underline'>linkedin</span> <img className='size-3 inline mr-1' src='/arrow-up-right-from-square-solid.svg'/></a>,
                    or <a download className='inline' href='/carson-holloway-full-stack-developer.pdf'><span className='underline'>download my resume</span> <img className='size-3 inline mr-1' src='/arrow-up-right-from-square-solid.svg'/></a>
                </p>
            </section>

        </main>
    </>
};

export default App

// vue/src/App.vue
<script setup lang="ts">
import Search from './components/Search.vue'
</script>

<template>
    <main class='max-w-full sm:max-w-280 pl-8 pr-8 pb-24 lg:pl-32 lg:pr-32 pt-8 ml-auto mr-auto'>
        <nav class='flex flex-row w-fill justify-end items-center'>
            <!-- <a class='ml-4 block' href='mailto:carsonalh@gmail.com'>
                <FontAwesomeIcon icon={faEnvelope} class="text-navy text-3xl hover:text-grey transition-colors duration-100" />
            </a> -->
            <!-- <a class='ml-4 block' href='https://github.com/carsonalh'>
                <FontAwesomeIcon icon={faGithub} class="text-navy text-3xl hover:text-grey transition-colors duration-100" />
            </a> -->
            <!-- <a class='ml-4 block' href='https://www.linkedin.com/in/carson-holloway-849b2b197/'>
                <FontAwesomeIcon icon={faLinkedin} class="text-navy text-3xl hover:text-grey transition-colors duration-100" />
            </a> -->
        </nav>

        <section class='mt-12'>
            <h1 class='font-extrabold text-navy text-4xl mb-4'>carson holloway</h1>
            <h2 class='text-grey text-2xl mb-3'>full-stack developer</h2>
            <h3 class='text-lightgrey text-xl mb-3'>brisbane, au</h3>
        </section>

        <section class='mt-12 text-right'>
            <h2 class='font-extrabold text-2xl text-navy mb-2'>this site comes in</h2>
            <div class="flex justify-end gap-4">
                <div class="text-grey">react</div>
                <div class="font-extrabold text-grey">vue</div>
            </div>
        </section>

        <section class='mt-12'>
            <h2 class='font-extrabold text-2xl text-navy mb-8'>my best technologies</h2>
            <ul class='grid grid-rows-2 grid-cols-2 items-end gap-y-6 sm:flex sm:flex-row sm:justify-evenly'>
                <li class='flex flex-col gap-2 items-center text-grey'><img class='sm:max-h-28' src='./assets/nodejs.svg' alt='NodeJS stylised logo' />node js</li>
                <li class='flex flex-col gap-2 items-center text-grey'><img class='sm:max-h-28' src='./assets/typescript.svg' alt='Typescript stylised logo' />typescript</li>
                <li class='flex flex-col gap-2 items-center text-grey'><img class='sm:max-h-28' src='./assets/react.svg' alt='React stylised logo' />react</li>
                <li class='flex flex-col gap-2 items-center text-grey'><img class='sm:max-h-28' src='./assets/go.svg' alt='Go stylised logo' />go</li>
            </ul>
        </section>

        <section class='mt-12'>
            <h2 class='font-extrabold text-2xl text-navy mb-2'>also excellent with</h2>
            <Search />
        </section>

        <section class='mt-12'>
            <h2 class='font-extrabold text-2xl text-navy mb-8'>want to learn more?</h2>
            <p class='text-navy'>
                send me an
                <a class='ml-1' href='mailto:carsonalh@gmail.com'><span class='underline'>email</span> <img class='size-3 inline mr-1' src='/arrow-up-right-from-square-solid.svg'/></a>,
                message me on
                <a class='ml-1' href='https://www.linkedin.com/in/carson-holloway-849b2b197/'><span class='underline'>linkedin</span> <img class='size-3 inline mr-1' src='/arrow-up-right-from-square-solid.svg'/></a>,
                or <a download class='inline' href='/carson-holloway-full-stack-developer.pdf'><span class='underline'>download my resume</span> <img class='size-3 inline mr-1' src='/arrow-up-right-from-square-solid.svg'/></a>
            </p>
        </section>

    </main>
</template>
